#!/usr/bin/python 

#Program to calculate information for half marathon training

#Converts weight in pounds to kilogram if necessary
def metric_imperial(y):
    print('Did you enter your weight in lbs (p) or kilograms (k)?')
    char = input()
    if char == 'p':
        kgweight = weight / 2.2
        print('Your weight in kilograms is %.2f.' % kgweight)
        return cal_burn(kgweight)
    elif char == 'k':
        kgweight = weight
        print('Your weight in kilograms is %.2f.' % kgweight)
        return cal_burn(kgweight)
    else:
        print('Please enter p for pounds or k for kilograms.')
        
#Determines calories burned over half marathon distance
def cal_burn(x):
    burnt = x * 21.0975
    print('You will burn %.2f calories during your race.' % burnt)

#Calculates vo2max for runners
def aerobic():
    distance = laps()
    #print(' ', distance)
    vo2max = .178 * (distance - 150) + 33.3
    print('Your aerobic fitness is %.2f.' % vo2max)
    

#Calculates caloric need for runners 
def cal_needs(x):
    choice = input("Are you very active? Y or N")
    if choice == 'y':
        cal = weight * 25
        print('You need %.2f calories while in training.' % cal)
    else:
        cal = weight * 20
        print('You need %.2f calories while in training.' % cal )

#Determines laps run
def laps():
    print('How far did you run in 15 minutes?')
    laps = float(input())
    meter_minutes = ((laps * 400) / 15)
    print('You ran %.2f meters in 15 minutes.' % (laps*400))
    return meter_minutes
    
weight = float(input('How much do you weigh?'))
print(' ' , weight)
kg = metric_imperial(weight)
fitness = aerobic()
cal_needs(weight)


